### PR TITLE
delete admin from community api

### LINKED ISSUE #32: Implement DELETE admin API
* Allow deletion of admin associated with a community.

### PR DESCRIPTION
**Pull request by gangadhargo**
@jmprathab wrote the code the same way as per other APIs. but what I observed that there are so many places null checks are missed and service exception handling is not there for bad data. Even in this current PR also I didn't cover most of the cases. Before refactoring I want to discuss with you personally
first time I am contributing to an opensource project so little bit exciting sorry :)

### CODE REVIEW

**Comment by jmprathab** [comment]
@gangadhargo I am in the process of reviewing. Thanks for your interest. You are right, not all errors are handled. That is because I wanted to get to an [MVP](https://en.wikipedia.org/wiki/Minimum_viable_product) as ASAP.

It is absolutely fine for not handling all the corner cases as we are planning to handle it once we have an end to end product up and running. 😊

**Comment by jmprathab** [comment]
@gangadhargo changes loooks good!

**Review by jmprathab — COMMENTED** [review]
Looks good.

I have added you to CONTRIBUTORS section in README.md file.

**Comment by gangadhargo** [comment]
@jmprathab thanks

**Pull request merged**
