### PR TITLE
Reorganize project to be multi module

### PR DESCRIPTION
**Pull request by mslowiak**
This pull request splits the project into modules.

This will be helpful in three ways:
- separating the integration tests away from unit tests (separate module - will move integration tests to a new module in separate PR)
- fix long integration tests that use h2 (will be working on that in separate PR)
- start thinking of OpenApi specification defined in yaml format - take a look at https://editor.swagger.io/?_ga=2.84949213.577473145.1601585129-532829462.1596700447 (this will be done later, in separate PR)

### CODE REVIEW

**Comment by jmprathab** [comment]
@mslowiak What is the advantage of Point 3? Isn't swagger spec generated automatically based on annotation in the code? Why to manually manage these specs?

**Comment by mslowiak** [comment]
> @mslowiak What is the advantage of Point 3? Isn't swagger spec generated automatically based on annotation in the code? Why to manually manage these specs?

Yeah, you need to write those annotations every single time.
With that approach all you need to do is fill for ex. description into in api.yaml and then your annotations are generated during build time.

**Comment by jmprathab** [comment]
> Yeah, you need to write those annotations every single time.
> With that approach all you need to do is fill for ex. description into in api.yaml and then your annotations are generated during build time.

Sounds cool!

**Comment by mslowiak** [comment]
I fixed the conflicts @jmprathab. Let's merge it

**Pull request merged**
