### PR TITLE
Issue #168: Add info about code style to CONTRIBUTING.md

### LINKED ISSUE #168: Add info about code style to CONTRIBUTING.md
There should be information in CONTRIBUTING.md about the code style that we use.
This info is included only in README.md actually.

Code style:
https://github.com/square/java-code-styles

### PR DESCRIPTION
**Pull request by HemantJoshi11**
## 🚀 Description

The code style information is added to CONTRIBUTING.md"

## 📄 Motivation and Context

This will help to have consistent code and easy maintainability. 

## 🧪 How Has This Been Tested?

Verified CONTRIBUTING.md in IDE.

NA

No
## 📦 Types of changes
Documentation

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## ✅ Checklist

- [ ] My code follows the code style of this project(Do your best to follow code styles. If none apply just skip this).
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by HemantJoshi11** [comment]
@mslowiak Pls review.
I really liked your detailed contribution checklist. 👍

**Comment by mslowiak** [comment]
I guess that was not enough detailed instruction, especially for @fx000000.

@HemantJoshi11 Could you please apply the instruction that I mentioned on our discord channel?
https://discord.com/channels/731769161361129523/731769161847668828/764207698643517504

**Comment by HemantJoshi11** [comment]
@mslowiak Thanks for your comments but I am unable to access  https://discord.com/channels/731769161361129523/731769161847668828/764207698643517504. Is some permission required?

**Comment by mslowiak** [comment]
@HemantJoshi11 
Yes you need to join by invitation link that is placed in readme.
This is it:
https://discord.gg/CngACKh

**Comment by HemantJoshi11** [comment]
@mslowiak I have updated  CONTRIBUTING.md with detailed instructions.

**Comment by mslowiak** [comment]
@HemantJoshi11 thank you for your contribution! :)

**Pull request merged**
